server:
  port: 8080

---
spring:
  profiles: jms-template, jms-listener
# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Artemis properties.
  jms:
    template:
      receive-timeout: 2
      default-destination: jms::datamodel.teamStatus.queue
  artemis:
    host: localhost
    port: 61616
    user: admin
    password: pass
    embedded:
      enabled: false
      
      
      
      
      